### ISSUE TITLE
gift spamming

### ISSUE THREAD

**Issue by Ironic8b498** [omwah/GiftEvents#12]
Getting a spamming issue with the all gifts, if one was to log out and back in they keep getting the gift, birthday, anniversary, etc.. I have a fresh config file and events file made changes by only adding events and customizing the advanced-events. Had this issue before don't recall what I did or how I fixed it?

**Comment by AlexMl** [comment]
Please send me your events_info.db, events.yml and your config file.

**Comment by AlexMl** [comment]
Fixed with 3bd879531aa36e9a7c82e717b52b9e005b744146
