### ISSUE TITLE
first_join_gift set to false

### ISSUE THREAD

**Issue by Ironic8b498** [omwah/GiftEvents#13]
With first_join_gift set to false when players first join the get Anniversary gift, is this cause I changed the first letter in event name to a capital letter?

**Comment by AlexMl** [comment]
if first_join_gift set to true the player will get the gift from Anniversary on the first day they join. If false they have to wait a year.
The capital letter was the problem but it is handled correctly now. Means you can write anniversary upper case/ lower case/with or without capital letters.

**Comment by Ironic8b498** [comment]
so it will be in next update?

**Comment by AlexMl** [comment]
A fixed version is already online. See 
http://dev.bukkit.org/bukkit-plugins/giftevents/files/13-v2-4-1/
the fix is in commit 3bd879531aa36e9a7c82e717b52b9e005b744146 if you are interested in code changes.

**Comment by Ironic8b498** [comment]
I already downloaded and replaced the plugin with the newer version. The spamming has stopped but I still get first_join_gift given to all players when on the first log in, even if set to false.

**Comment by AlexMl** [comment]
Please make a new ticket for this issue. I then take care of the bug.
