### ISSUE TITLE
first_join_gift set to false

### ISSUE THREAD

**Issue by Ironic8b498** [omwah/GiftEvents#14]
with first_join_gift set to false players that log out and log back in get the anniversary present, could the code be fixed to give anniversary present if they have been on server for more then 24 hours and their anniversary date, or something simple like that

**Comment by AlexMl** [comment]
can you, if possible, give me your events.yml and events_info.db? That would help me a lot.

**Comment by Ironic8b498** [comment]
I zipped them up and place in my dropbox account https://dl.dropboxusercontent.com/u/81218539/events.zip

**Comment by AlexMl** [comment]
Thank you. I'm preparing a patch now.

**Comment by AlexMl** [comment]
Please try this update https://github.com/omwah/GiftEvents/releases/tag/GE-v2.4.2 .

The plugin checks now if the player was online more than one day.(2 or more days)

Please check it out and tell me if it worked.

**Comment by Ironic8b498** [comment]
thanks, I will let you know when I get a new player on if they get a gift, I feel it will work great.
